apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- httproute.yaml
- netpol.yaml
- service.yaml
# - s3-base.yaml # uncomment this if you want to deploy a general purpose S3 bucket